services:
  frontend:
    image: ghcr.io/ollegsey/torpedo-frontend:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:3001:80"

  bot:
    image: ghcr.io/ollegsey/torpedo-bot:latest
    restart: unless-stopped
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      WEBAPP_URL: https://ollegsey.ru:4443
